const cliCollisionPackages = [
    'access',
    'adduser',
    'audit',
    'bugs',
    'cache',
    'ci',
    'completion',
    'config',
    'dedupe',
    'deprecate',
    'diff',
    'dist-tag',
    'docs',
    'doctor',
    'edit',
    'exec',
    'explain',
    'explore',
    'find-dupes',
    'fund',
    'help',
    'help-search',
    'hook',
    'init',
    'install',
    'install-ci-test',
    'install-test',
    'link',
    'login',
    'logout',
    'ls',
    'org',
    'outdated',
    'owner',
    'pack',
    'ping',
    'pkg',
    'prefix',
    'profile',
    'prune',
    'publish',
    'query',
    'rebuild',
    'repo',
    'restart',
    'root',
    'run-script',
    'sbom',
    'search',
    'shrinkwrap',
    'star',
    'stars',
    'start',
    'stop',
    'team',
    'test',
    'token',
    'uninstall',
    'unpublish',
    'unstar',
    'update',
    'version',
    'view',
    'whoami'
]

const nodeDefaultPackages = [
    'assert', 
    'dns', 
    'fs', 
    'inspector', 
    'internal', 
    'path', 
    'readline', 
    'stream', 
    'test', 
    'timers', 
    'util', 
    '.eslintrc.yaml', 
    'http_agent', 
    'http_client', 
    'http_common', 
    'http_incoming', 
    'http_outgoing', 
    'http_server', 
    'stream_duplex', 
    'stream_passthrough', 
    'stream_readable', 
    'stream_transform', 
    'stream_wrap', 
    'stream_writable', 
    'tls_common', 
    'tls_wrap', 
    'assert', 
    'async_hooks', 
    'buffer', 
    'child_process', 
    'cluster', 
    'console', 
    'constants', 
    'crypto', 
    'dgram', 
    'diagnostics_channel', 
    'dns', 
    'domain', 
    'events', 
    'fs', 
    'http', 
    'http2', 
    'https', 
    'inspector', 
    'module', 
    'net', 
    'os', 
    'path', 
    'perf_hooks', 
    'process', 
    'punycode', 
    'querystring', 
    'readline', 
    'repl', 
    'stream', 
    'string_decoder', 
    'sys', 
    'test', 
    'timers', 
    'tls', 
    'trace_events', 
    'tty', 
    'url', 
    'util', 
    'v8', 
    'vm', 
    'wasi', 
    'worker_threads', 
    'zlib']

const color = {
    Reset: "\x1b[0m",
    Bright: "\x1b[1m",
    Dim: "\x1b[2m",
    Underscore: "\x1b[4m",

    FgBlack: "\x1b[30m",
    FgRed: "\x1b[31m",
    FgGreen: "\x1b[32m",
    FgYellow: "\x1b[33m",
    FgBlue: "\x1b[34m",
    FgMagenta: "\x1b[35m",
    FgCyan: "\x1b[36m",
    FgWhite: "\x1b[37m",
    FgGray: "\x1b[90m",

    BgBlack: "\x1b[40m",
    BgRed: "\x1b[41m",
    BgGreen: "\x1b[42m",
    BgYellow: "\x1b[43m",
    BgBlue: "\x1b[44m",
    BgMagenta: "\x1b[45m",
    BgCyan: "\x1b[46m",
    BgWhite: "\x1b[47m",
    BgGray: "\x1b[100m"
}

module.exports = {
    cliCollisionPackages,
    nodeDefaultPackages,
    color,
}